name: Install and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: python setup.py develop
    - name: tests
      run: pytest
